version: "3"
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - PGUSER=musicfan2
      - PGHOST=db
      - PGPASSWORD=bobmarley
      - PGDATABASE=TheCompleteRecord
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: postgres:latest
    ports:
      - 35432:5423
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment:
      - POSTGRES_DB=TheCompleteRecord
      - POSTGRES_USER=musicfan2
      - POSTGRES_PASSWORD=bobmarley
volumes:
  dbdata:
